### ISSUE TITLE
todo 

### ISSUE THREAD

**Issue by soroush-bn** [soroush-bn/search-project#1]
- [ ] implement models with details
- [ ] create board and place models on them 
- [ ] create sample map 
- [ ] implement core logic
- [ ] implement uninformed searches
- [ ] implement informed searches
- [ ] implement map generator
